# Site settings
title: Java Matrix Benchmark
email: peter.abeles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Java Matrix Benchmark is a tool for evaluating Java linear algebra libraries for speed, stability, and memory usage. Its goal is to help improve the state of high performance computing on the Java platform and to encourage performance optimization across a range of matrix sizes.
#baseurl: "/jmatbench" # the subpath of your site, e.g. /blog/
#url: "http://peterabeles.com/" # the base hostname & protocol for your site
twitter_username: NotSoOptimal
github_username:  lessthanoptimal

google_analytics_id: UA-10413214-2

#repository: https://github.com/jekyll/jekyll
#help_url: https://github.com/jekyll/jekyll-help

# Build settings
markdown: kramdown
relative_permalinks: false

collections:
  runtime:
    output: true
  memory:
    output: true
  stability:
    output: true
  manual:
    output: true
